version: '1.0'
name: pipeline-20220123
displayName: pipeline-20220123
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-849c104d
    displayName: publish
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: shell@agent
        name: execute_shell
        displayName: Shell 脚本执行
        hostGroupID: gitee-go
        script: 
        |
          npm install
          npx vsce publish -p $TOKEN
          echo 'success publish vscode plugin'
permissions:
  - role: admin
    members: []
