version: '1.0'
name: pipeline-20220122
displayName: pipeline-20220122
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - master
stages:
  - name: stage-c86c0762
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: shell@agent
        name: execute_shell
        displayName: Shell 脚本执行
        hostGroupID: gitee-go
        script: |-
          npm install
          npx vsce publish -p $TOKEN
          echo 'success publish vscode plugin'
permissions:
  - role: admin
    members: []

